### ISSUE TITLE
Recherche incluant les m² vides

### ISSUE THREAD

**Issue by Imtiaz88** [onesse/projetappart#4]
Bonjour. 

Merci pour votre outil. 
J'essaie d'inclure les ventes qui ne mentionnent pas les mètres carrés, cependant celles ci n'apparaissent pas dans mon fichier final.
Cela provient a priori d'ici : 
'spider_exceptions/TypeError': 10
TypeError: expected string or bytes-like object
Je n'arrive pas à modifier le code pour inclure ces ventes qui ne mentionnent pas le m². 
Sauriez vous comment faire.
Merci

Voici un extrait des résultats : 

2020-02-22 19:20:11 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.leboncoin.fr/ventes_immobilieres/1730717886.htm/> (referer: https://www.leboncoin.fr/recherche/?category=9&locations=Marseille&price=80000-99999&real_estate_type=2%2C1%2C3%2C4%2C5&immo_sell_type=new%2Cold&page=12)
Traceback (most recent call last):
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\core\spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\core\spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\core\spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\core\spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "c:\users\***\miniconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\Users\***\Downloads\projetappart-master\projetappart\spiders\appart.py", line 90, in parse_page
    surface_bien = parse_surface_bien(response)
  File "c:\Users\***\Downloads\projetappart-master\projetappart\utils\utils.py", line 85, in parse_surface_bien
    surface = re.findall(r'\d+', suface_str)
  File "c:\users\***\miniconda3\lib\re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
(...)
2020-02-22 19:20:12 [scrapy.core.engine] INFO: Closing spider (finished)
2020-02-22 19:20:12 [scrapy.extensions.feedexport] INFO: Stored csv feed (402 items) in: result_MRS_ALL_22.02.2020.19.16.csv
2020-02-22 19:20:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 258850,
 'downloader/request_count': 425,
 'downloader/request_method_count/GET': 425,
 'downloader/response_bytes': 15495012,
 'downloader/response_count': 425,
 'downloader/response_status_count/200': 425,
 'dupefilter/filtered': 1,
 'elapsed_time_seconds': 11.678637,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 2, 22, 18, 20, 12, 753726),
 'item_scraped_count': 402,
 'log_count/DEBUG': 828,
 'log_count/ERROR': 10,
 'log_count/INFO': 11,
 'request_depth_max': 12,
 'response_received_count': 425,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 424,
 'scheduler/dequeued/memory': 424,
 'scheduler/enqueued': 424,
 'scheduler/enqueued/memory': 424,
 'spider_exceptions/TypeError': 10,
 'start_time': datetime.datetime(2020, 2, 22, 18, 20, 1, 75089)}
2020-02-22 19:20:12 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by onesse** [comment]
Je vais regarder !
